name: Build

on:
  pull_request

jobs:
  build:
    name: Go
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: false
        id: go

      - name: Print Go version
        run: go version

      - name: Build
        run: go build -v .

  build_docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build . --file Dockerfile --tag inx-validator:latest
